services:
  naplex-postgres-db:
    image: postgres:17-alpine
    container_name: naplex-postgres-db
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - naplex_postgres_data:/var/lib/postgresql/data
      - ../../migrations/:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  naplex_postgres_data:
    name: naplex_app_data

networks:
  app_network:
    driver: bridge
