// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package srcDB

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedQuestion struct {
	ID              int32
	Title           string
	Question        string
	MultipleChoices string
	CorrectAnswer   string
	Explanation     pgtype.Text
	Keywords        pgtype.Text
}
