// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sqlc_query.sql

package dstDB

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (title, question, multiple_choices, correct_answer, explanation, keywords, link)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateQuestionParams struct {
	Title           string
	Question        string
	MultipleChoices string
	CorrectAnswer   string
	Explanation     pgtype.Text
	Keywords        pgtype.Text
	Link            pgtype.Text
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.Title,
		arg.Question,
		arg.MultipleChoices,
		arg.CorrectAnswer,
		arg.Explanation,
		arg.Keywords,
		arg.Link,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
