// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedQuestion struct {
	ID              int32
	Title           string
	Question        string
	MultipleChoices string
	CorrectAnswer   string
	Explanation     pgtype.Text
	Keywords        pgtype.Text
	Link            pgtype.Text
}

type RawQuestion struct {
	ID          int32
	Title       string
	RawQuestion string
	Link        pgtype.Text
}
